export const FETCH_PROFILE_DATA_BEGIN = "FETCH_PROFILE_DATA_BEGIN"
export const FETCH_PROFILE_DATA_SUCCESS = "FETCH_PROFILE_DATA_SUCCESS"
export const FETCH_PROFILE_DATA_FAILURE ="FETCH_PROFILE_DATA_FAILURE"
export const FIND_USER = "FIND_USER"